//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca.whittaker.Maui.Controls.Demo.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ca.whittaker.Maui.Controls.Demo.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin with apple.
        /// </summary>
        internal static string Button_SignInWithApple {
            get {
                return ResourceManager.GetString("Button_SignInWithApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin with facebook.
        /// </summary>
        internal static string Button_SignInWithFacebook {
            get {
                return ResourceManager.GetString("Button_SignInWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin with google.
        /// </summary>
        internal static string Button_SignInWithGoogle {
            get {
                return ResourceManager.GetString("Button_SignInWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin with linkedin.
        /// </summary>
        internal static string Button_SignInWithLinkedin {
            get {
                return ResourceManager.GetString("Button_SignInWithLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin with tiktok.
        /// </summary>
        internal static string Button_SignInWithTiktok {
            get {
                return ResourceManager.GetString("Button_SignInWithTiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign-out.
        /// </summary>
        internal static string Button_SignOut {
            get {
                return ResourceManager.GetString("Button_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bio.
        /// </summary>
        internal static string Field_Bio {
            get {
                return ResourceManager.GetString("Field_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about you.
        /// </summary>
        internal static string Field_Bio_Placeholder {
            get {
                return ResourceManager.GetString("Field_Bio_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Field_Country {
            get {
                return ResourceManager.GetString("Field_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada, United States, United Kingdom, China.
        /// </summary>
        internal static string Field_Country_Items {
            get {
                return ResourceManager.GetString("Field_Country_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your country.
        /// </summary>
        internal static string Field_Country_Placeholder {
            get {
                return ResourceManager.GetString("Field_Country_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string Field_Email {
            get {
                return ResourceManager.GetString("Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email.
        /// </summary>
        internal static string Field_Email_Placeholder {
            get {
                return ResourceManager.GetString("Field_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public profile?.
        /// </summary>
        internal static string Field_IsPublic {
            get {
                return ResourceManager.GetString("Field_IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your name.
        /// </summary>
        internal static string Field_Name_Placeholder {
            get {
                return ResourceManager.GetString("Field_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string Form_UserProfile_Button_Cancel {
            get {
                return ResourceManager.GetString("Form_UserProfile_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string Form_UserProfile_Button_Save {
            get {
                return ResourceManager.GetString("Form_UserProfile_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        internal static string Form_UserProfile_Button_Undo {
            get {
                return ResourceManager.GetString("Form_UserProfile_Button_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about you.
        /// </summary>
        internal static string Form_UserProfile_TItle {
            get {
                return ResourceManager.GetString("Form_UserProfile_TItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        internal static string Page_LoginLogout_Title_SignIn {
            get {
                return ResourceManager.GetString("Page_LoginLogout_Title_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign-out.
        /// </summary>
        internal static string Page_LoginLogout_Title_SignOut {
            get {
                return ResourceManager.GetString("Page_LoginLogout_Title_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user profile.
        /// </summary>
        internal static string Page_UserProfile_Title {
            get {
                return ResourceManager.GetString("Page_UserProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        internal static string Tab_CheckBox {
            get {
                return ResourceManager.GetString("Tab_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        internal static string Tab_LoginLogout {
            get {
                return ResourceManager.GetString("Tab_LoginLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        internal static string Tab_TextBox {
            get {
                return ResourceManager.GetString("Tab_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        internal static string Tab_UserProfile {
            get {
                return ResourceManager.GetString("Tab_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Table_LoginDetails_TextCell_Device {
            get {
                return ResourceManager.GetString("Table_LoginDetails_TextCell_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date.
        /// </summary>
        internal static string Table_LoginDetails_TextCell_LastLoginDate {
            get {
                return ResourceManager.GetString("Table_LoginDetails_TextCell_LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Table_LoginDetails_TextCell_Location {
            get {
                return ResourceManager.GetString("Table_LoginDetails_TextCell_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        internal static string Table_LoginDetails_Title {
            get {
                return ResourceManager.GetString("Table_LoginDetails_Title", resourceCulture);
            }
        }
    }
}
